### ISSUE TITLE
請問有辦法利用 命令提示字元 的方式開啟程式並執行嗎

### ISSUE THREAD

**Issue by JC-Chung** [dghkd/KomeTube#5]
請問有辦法利用 命令提示字元 的方式開啟程式並執行嗎？
例如： `C:\>KomeTube.exe https://www.youtube.com/watch?v=xxxxxxxxxxx`
`CMD`開啟 `KomeTube.exe` 後，自動將網址放入輸入框並開始抓取留言
謝謝

另外最新版使用 `HtmlTextBlock` 似乎就無法像之前 `TextBox` 可以直接在程式內複製聊天訊息
先前查詢好像沒有解決方法，因為本身對該語言不熟，所以一些修改都是從現有的程式碼複製修改
想請教是否有好的方法改善
謝謝

**Comment by dghkd** [comment]
> 請問有辦法利用 命令提示字元 的方式開啟程式並執行嗎？

可以
只要新增處理app startup事件
解析命令列參數後將網址存起來
在Window loaded事件處理中將輸入框填入網址後Eexecute start command就可以了

> 另外最新版使用 HtmlTextBlock 似乎就無法像之前 TextBox 可以直接在程式內複製聊天訊息

這沒辦法，為了同時顯示圖與文，目前只找到這個元件比較方便用
除非將 HtmlTextBlock 元件從底層換成 TextBox 重新改寫
或是利用CEF套件把Chrome瀏覽器嵌進去，用瀏覽器去渲染留言
不然就是改用RichTextBox或WebView2元件
但這些要自己改實在很麻煩
結論：還是等其他神人或微軟出新的、更好用的元件再來改

如果是為了複製留言的話
目前想到能做的方法是在每個留言後面增加一個Button
點Button之後將留言字串複製到剪貼簿中

不過因為目前我把留言都重新format成給 HtmlTextBlock 使用的字串
要額外將留言的原本字串儲存起來給剪貼簿才行
細節要回去看一下format表符和loader解析留言那部分的code

**Comment by dghkd** [comment]
更新於v5.0.0.10900
https://github.com/dghkd/KomeTube/releases/tag/5.0.0.10090

**Comment by JC-Chung** [comment]
感謝更新
另外突然想到我之前有自行對更多種的留言類型進行捕捉，如SC貼圖、贈禮、收禮等
是否有需要將程式碼給你一併修改or新增
基本上都是利用抓取一般留言的方式進行修改的
不過詳細更動了哪些可能要再確認一下 (自己的版本最後更新是6/12)
