### ISSUE TITLE
新增多種訊息捕捉

### ISSUE THREAD

**Issue by JC-Chung** [dghkd/KomeTube#6]
共更改了以下 6 個檔案
KomeTube/Kernel/CommentExportData.cs
KomeTube/Kernel/CommentLoader.cs
KomeTube/Kernel/YtLiveChatDataModel/CommentData.cs
KomeTube/MainWindow.xaml
KomeTube/ViewModel/CommentVM.cs
KomeTube/ViewModel/MainWindowVM.cs

主要為新增
輸出內容
付費貼圖資訊
贈禮會員資訊
會員贈禮通知
獲得會員贈禮通知
會員訊息資訊
新會員訊息、里程碑訊息 等內容

可利用此連結進行比較
https://github.com/dghkd/KomeTube/compare/master...JC-Chung:KomeTube:master

僅以自己獲取過的訊息去新增，可能還有漏掉的

**Comment by dghkd** [comment]
感謝分享程式碼喔
因為我github都是放自己興趣下寫的東西
沒有想過會得到有人反饋
更沒有考慮太多和別人協作跟PR管理
而且還滿懶的
大概久久才會動一次
所以不打算收PR 抱歉
不過能收到反饋還滿高興的
順便開了討論區，把你這篇轉過去，跟issue做區隔
https://github.com/dghkd/KomeTube/discussions/10
